# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Search-Estraier
version:      0.07_2
version_from: Estraier.pm
installdirs:  site
requires:
    Carp:                          0
    LWP::UserAgent:                0
    MIME::Base64:                  0
    Test::Exception:               0
    Test::Simple:                  0
    URI:                           0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
